version: 2

project_name: vmware-exporter

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: linux
    main: ./
    binary: vmware-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
  - id: windows
    main: ./
    binary: vmware-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - arm64
      - amd64

archives:
  - id: vmware-exporter
    builds:
      - linux
      - windows
      - macos
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

# checksum:
#   name_template: "{{ .ProjectName }}_checksums.txt"
# snapshot:
#   version_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - "^docs:"
#       - "^test:"